repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0           # Changed to a known stable version
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2           # Changed to the main isort repo with a known version
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0          # Updated to a more recent, known version
    hooks:
      - id: eslint
        entry: eslint
        language: node
        types: [javascript, jsx]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0           # This one seems fine, but you could update if needed
    hooks:
      - id: prettier
        entry: prettier --write
        language: node
        types: [javascript, json, markdown]