apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/backend:latest
          ports:
            - containerPort: 8080
